dist: xenial
language: python

matrix:
    include:
        - python: 3.6
        - python: 3.7
        - python: 3.8

install:
  - pip install -r requirements.txt
  - pip install pytest

script: "pytest"

deploy:
  provider: pypi
  username: "__token__"
  password:
  on:
    tags: true
  skip_existing: true